/**
 * npm run scenario -- <id...|all> [--llm]
 * Resets the environment per scenario, runs it, prints expected vs actual, writes
 * docs/results/scenario-results.{md,json}, exits non-zero if anything is not PASS.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SCENARIOS, scenarioById, runScenario } from '../src/scenarios/definitions.js';
import { pool } from '../src/db/pool.js';
import { ensureSeeded } from '../src/db/reset.js';

const args = process.argv.slice(2);
const mode = args.includes('--llm') ? 'llm' : 'deterministic';
const ids = args.filter((a) => !a.startsWith('--'));
const list = !ids.length || ids.includes('all') ? SCENARIOS : ids.map((id) => {
  const s = scenarioById(id);
  if (!s) { console.error(`Unknown scenario '${id}'. Available: ${SCENARIOS.map((x) => x.id).join(', ')}`); process.exit(2); }
  return s;
});

await ensureSeeded();
const results = [];
for (const s of list) {
  const r = await runScenario(s, mode);
  results.push(r);
  console.log(`\n[${r.verdict}] ${r.id} — ${r.title} (${r.passed}/${r.total}, ${r.ms} ms, ${mode})`);
  for (const c of r.checks) console.log(`   ${c.pass ? '✓' : '✗'} ${c.name}: expected ${c.expected} | actual ${c.actual}`);
}
const pass = results.filter((r) => r.verdict === 'PASS').length;
console.log(`\n${pass}/${results.length} scenarios passed (${mode}).`);

if (list.length === SCENARIOS.length) {
  const dir = join(import.meta.dirname, '../../docs/results');
  mkdirSync(dir, { recursive: true });
  const md = [
    `# Scenario Results (${mode})`, '',
    `Generated by \`npm run scenario -- all${mode === 'llm' ? ' --llm' : ''}\` on ${new Date().toISOString()}. Each scenario resets the environment first.`, '',
    `**${pass}/${results.length} PASS**`, '',
    '| Scenario | Category | Verdict | Checks |', '|---|---|---|---|',
    ...results.map((r) => `| \`${r.id}\` | ${r.category} | ${r.verdict} | ${r.passed}/${r.total} |`), '',
    ...results.flatMap((r) => [
      `## ${r.id} — ${r.title}`, '',
      `- **Setup:** ${r.setup}`, `- **Trigger:** ${r.trigger}`, `- **Expected:** ${r.expected}`, `- **Boundary:** ${r.boundary}`, `- **Verdict:** ${r.verdict}`, '',
      '| Check | Expected | Actual | |', '|---|---|---|---|',
      ...r.checks.map((c) => `| ${c.name} | ${c.expected.replace(/\|/g, '/')} | ${c.actual.replace(/\|/g, '/')} | ${c.pass ? '✅' : '❌'} |`),
      ...((r.artifacts as any).tool_sequence ? ['', `Tool sequence: \`${(r.artifacts as any).tool_sequence}\``] : []), '',
    ]),
  ].join('\n');
  writeFileSync(join(dir, `scenario-results${mode === 'llm' ? '-llm' : ''}.md`), md);
  writeFileSync(join(dir, `scenario-results${mode === 'llm' ? '-llm' : ''}.json`), JSON.stringify(results.map(({ artifacts, ...r }) => r), null, 2));
  console.log(`Wrote docs/results/scenario-results${mode === 'llm' ? '-llm' : ''}.md`);
}
await pool.end();
process.exit(pass === results.length ? 0 : 1);
